// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_content_delivery_bucket": "temp9-20200120062450-hostingbucket-test",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "http://temp9-20200120062450-hostingbucket-test.s3-website.ap-south-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-south-1:47e5687c-823c-4d60-9c0a-cf43e881bab5",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_aOqZN34w5",
    "aws_user_pools_web_client_id": "1l001pjkvkur950bnl74li243b",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rsugutgwszajrou5lxmkmbxqtq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pb4owynw3bg6ngk3z24wne3knq"
};


export default awsmobile;
